export const Division = [
  {
    name: "Dhaka",
    value: "Dh",
    districts: [
      {
        name: "Dhaka ",
        upazilas: [
          "Dohar Upazila",
          "Keraniganj Upazila",
          "Dhamrai Upazila",
          "Nawabganj Upazila",
          "Savar Upazila ",
        ],
      },
      {
        name: "Gazipur",
        upazilas: [
          "Gazipur Sadar",
          "Kaliakoir",
          "Kaliganj",
          "Kapasia",
          "Sreepur",
        ],
      },
      {
        name: "Faridpur",
        upazilas: [
          "Alfadanga",
          "Bhanga",
          "Boalmari",
          "Char Bhadrasan",
          "Faridpur Sadar",
          "Madhukhali",
          "Nagarkanda",
          "Sadarpur",
          "Saltha",
        ],
      },
      {
        name: "Gopalganj",
        upazilas: [
          "Gopalganj Sadar",
          "Kasiani",
          "Kotalipara",
          "Maksudpur",
          "Tungipara",
        ],
      },
      {
        name: "Kishoreganj",
        upazilas: [
          "Austogram",
          "Bajitpur",
          "Bhairab",
          "Hosainpur",
          "Itna",
          "Karimganj",
          "Katiadi",
          "Kishoreganj Sadar",
          "Kuliarchar",
          "Mithamain",
          "Nikli",
          "Pakundia",
        ],
      },
      {
        name: "Tangail",
        upazilas: [
          "Bashail",
          "Bhuapur",
          "Delduar",
          "Ghatail",
          "Gopalpur",
          "Kalihati",
          "Mirzapur",
          "Modhupur",
          "Nagarpur",
          "Shakhipur",
          "Tangail Sadar",
          "Dhanbari",
        ],
      },
      {
        name: "Shariatpur",
        upazilas: [
          "Bhedarganj",
          "Damudiya",
          "Gosairhat",
          "Zajira",
          "Naria",
          "Shariatpur Sadar",
        ],
      },
      {
        name: "Rajbari",
        upazilas: [
          "Baliakandi",
          "Goalunda",
          "Pangsha",
          "Rajbari Sadar",
          "Kalukhale",
        ],
      },
      {
        name: "Narsingdi",
        upazilas: [
          "Belabo",
          "Monohardi",
          "Norshingdi Sadar",
          "Palash",
          "Raipura",
          "Shibpur",
        ],
      },
      {
        name: "Narayanganj",
        upazilas: [
          "Araihazar",
          "Bandar",
          "Narayanganj Sadar",
          "Rupganj",
          "Sonargao",
        ],
      },
      {
        name: "Madaripur",
        upazilas: ["Kalkini", "Madaripur Sadar", "Rajoir", "Shibchar"],
      },
      {
        name: "Manikganj",
        upazilas: [
          "Daulatpur",
          "Ghior",
          "Harirampur",
          "Manikganj Sadar",
          "Saturia",
          "Shibalaya",
          "Singair",
        ],
      },
    ],
  },
  {
    name: "Mymenshingh",
    value: "My",
    districts: [
      {
        name: "Mymensingh",
        upazilas: [
          "Mymensingh Sadar",
          "Muktagachha",
          "Valuka",
          "Haluaghat",
          "Gouripur",
          "Dhobaura",
          "Fulbaria",
          "Gafargaon",
          "Trishal",
          "Fulpur",
          "Nandail",
          "Ishwarganj",
        ],
      },
      {
        name: "Netrakona",
        upazilas: [
          "Netrokona Sadar",
          "Kendua",
          "Mohangonj",
          "Khaliajuri",
          "Purbodhola ",
          "Atpara ",
          "Modon",
          "Kolmkakanda",
          "Barhatta",
          "Durgapur",
        ],
      },
      {
        name: "Jamalpur",
        upazilas: [
          "Jamalpur Sadar",
          "Baksiganj",
          "Dewanganj",
          "Islampur",
          "Madarganj",
          "Melandaha",
          "Sarishabari",
        ],
      },
      {
        name: "Sherpur",
        upazilas: [
          "Sherpur Sadar",
          "Nakla",
          "Sreebardi",
          "Nalitabari",
          "Jhenaigati",
        ],
      },
    ],
  },
  {
    name: "Khulna",
    value: "Kh",
    districts: [
      {
        name: "Khulna",
        upazilas: [
          "Dumuria",
          "Batiaghata",
          "Dacope",
          "Phultala",
          "Dighalia",
          "Koyra",
          "Terokhada",
          "Rupsha",
          "Paikgachha",
          "Khan Jahan Ali",
          "Daulatpur",
          "Sonadanga",
          "Khalishpur",
        ],
      },
      {
        name: "Bagherhat",
        upazilas: [
          "Bagerhat Sadar",
          "Mongla",
          "Chitalmari",
          "Sarankhola",
          "Fakirhat",
          "Rampal",
          "Mollahat",
          "Morrelganj",
          "Kachua",
        ],
      },
      {
        name: "Sathkhira",
        upazilas: [
          "Satkhira Sadar",
          "Shyamnagar",
          "Assasuni",
          "Kaliganj",
          "Debhata",
          "Kalaroa",
          "Tala",
        ],
      },
      {
        name: "Jessore",
        upazilas: [
          "Jessore Sadar",
          "Jhikargachha",
          "Manirampur",
          "Bagherpara",
          "Abhaynagar",
          "Keshabpur",
          "Sharsha",
          "Chaugachha",
        ],
      },
      {
        name: "Magura",
        upazilas: ["Magura Sadar", "Shalikha", "Sreepur", "Mohammadpur"],
      },
      {
        name: "Jhenaidah",
        upazilas: [
          "Jhenaidah Sadar",
          "Shailkupa",
          "Harinakunda",
          "Maheshpur",
          "Kotchandpur",
          "Kaliganj",
        ],
      },
      {
        name: "Narail",
        upazilas: ["Narail Sadar", "Lohagara", "Kalia"],
      },
      {
        name: "Kushtia",
        upazilas: [
          "Kushtia Sadar",
          "Mirpur",
          "Khoksa",
          "Bheramara",
          "Kumarkhali",
          "Daulatpur",
        ],
      },
      {
        name: "Chuadanga",
        upazilas: ["Chuadanga Sadar", "Alamdanga", "Damurhuda", "Jibonnagar"],
      },
      {
        name: "Meherpur",
        upazilas: ["Meherpur Sadar", "Mujibnagar", "Gangni"],
      },
    ],
  },
  {
    name: "Barishal",
    value: "Ba",
    districts: [
      {
        name: "Barishal",
        upazilas: [
          "Agailjhara",
          "Gournadi",
          "Bakergonj",
          "Banaripara",
          "Barishal Sadar",
          "Mehendigonj",
          "Muladi",
          "Wazirpur",
          "Hizla",
        ],
      },
      {
        name: "Pirojpur",
        upazilas: [
          "Pirojpur Sadar",
          "Zianagar",
          "Mathbaria",
          "Bhandaria",
          "Kawkhali",
          "Nesarabad",
          "Nazirpur",
        ],
      },
      {
        name: "Jhalokathi",
        upazilas: [
          "Jhalokati Sadar",
          "Kathalia Upazila",
          "Nalchity Upazila",
          "Raiapur Upazila",
        ],
      },
      {
        name: "Barguna",
        upazilas: [
          "Barguna Sadar",
          "Amtali",
          "Bamna",
          "Patharghata",
          "Taltali",
          "Betagi",
        ],
      },
      {
        name: "Bhola",
        upazilas: [
          "Bhola Sadar",
          "Daulatkhan",
          "Borhanuddin",
          "Lalmohan",
          "Tazumuddin",
          "Manpura",
          "Charfashion",
        ],
      },
      {
        name: "Patuakhali",
        upazilas: [
          "Patuakhali Sadar",
          "Dumki",
          "Doshmina",
          "Bauphal",
          "Mirjaganj",
          "Galacipa",
          "Kalapara",
          "Rangabali",
        ],
      },
    ],
  },
  {
    name: "Rajshahi",
    value: "Ra",
    districts: [
      {
        name: "Rajshahi",
        upazilas: [
          "Bagmara",
          "Paba",
          "Charghat",
          "Durgapur",
          "Godagari",
          "Mohanpur",
          "Bagha",
          "Puthia",
          "Tanore",
        ],
      },
      {
        name: "Sirajganj",
        upazilas: [
          "Sirajganj Sadar",
          "Chauhali",
          "Kamarkhanda",
          "Belkuchi",
          "Kazipur",
          "Raiganj",
          "Ullahpara",
          "Tarash",
          "Shahjadpur",
        ],
      },
      {
        name: "Pabna",
        upazilas: [
          "Pabna Sadar",
          "Santhia",
          "Bera",
          "Sujanagar",
          "Atgharia",
          "Bhangura",
          "Faridpur",
          "Chatmohar",
          "Ishwardi",
        ],
      },
      {
        name: "Natore",
        upazilas: [
          "Natore Sadar",
          "Bagatipara",
          "Singra",
          "Boraigram",
          "Gurudaspur",
          "Lalpur",
        ],
      },
      {
        name: "Naogaon",
        upazilas: [
          "Naogaon Sadar",
          "Atrai",
          "Dhamoirhat",
          "Badalgachhi",
          "Niamatpur",
          "Manda",
          "Mohadevpur",
          "Patnitala",
          "Porsha",
          "Sapahar",
          "Raninagar",
        ],
      },
      {
        name: "Bogra",
        upazilas: [
          "Bogra Sadar",
          "Gabtali",
          "Sariakandi",
          "Adamdighi",
          "Sonatala",
          "Sherpur",
          "Kahaloo",
          "Shibganj",
          "Dupchanchia",
          "Nandigram",
          "Sahajanpur",
          "Dhunat",
        ],
      },
      {
        name: "Chapinawabganj",
        upazilas: [
          "Chapai Nawabganj Sadar",
          "Nachole",
          "Shibganj",
          "Gomastapur",
          "Bholahat",
        ],
      },
      {
        name: "Joypurhat",
        upazilas: [
          "Joypurhat Sadar",
          "Akkelpur",
          "Khetlal",
          "Panchbibi",
          "Kalai",
        ],
      },
    ],
  },
  {
    name: "Chittagong",
    value: "Ch",
    districts: [
      {
        name: "Chittagong",
        upazilas: [
          "Akbarshah",
          "Bakoliya",
          "Bander",
          "Bayazid",
          "Bhujpur",
          "Chandgaon",
          "EPZ",
          "Double Mooring",
          "Halishahar",
          "Karnaphuli",
          "Khulshi",
          "Kotwali",
          "Pahartali",
          "Panchlaish",
          "Patenga",
        ],
      },
      {
        name: "Chandpur",
        upazilas: [
          "Haimchar",
          "Kachua",
          "Shahrasti",
          "Chandpur Sadar",
          "Matlab Dakshin",
          "Haziganj",
          "Matlab Uttar",
          "Farjdganj",
        ],
      },
      {
        name: "Brahmanbaria",
        upazilas: [
          "Brahmanbaria(B.Baria) Sadar",
          "Bijoynagar",
          "Akhaura",
          "Ashuganj",
          "Bancharampur",
          "Kasba",
          "Nabinagar",
          "Nasirnagar",
          "Sarail",
        ],
      },
      {
        name: "Noakhali",
        upazilas: [
          "Noakhali Sadar",
          "Begumganj",
          "Senbag",
          "Companiganj",
          "Chatkhil",
          "Sonaimuri",
          "Hatiya",
          "Subarnachar",
          "Kabirhat",
        ],
      },
      {
        name: "Comilla",
        upazilas: [
          "Cumilla Sadar South",
          "Comilla Adarsa Sadar",
          "Barura",
          "Chandina",
          "Chauddagram",
          "Daudkandi",
          "Homna",
          "Brahmanpara",
          "Monohorgonj",
          "Laksam",
          "Debidwar",
          "Meghna",
          "Muradnagar",
          "Nangalkot",
          "Burichong",
          "Titas",
        ],
      },
      {
        name: "Lakshmipur",
        upazilas: [
          "Lakshmipur (Laxmipur)",
          "Ramgati",
          "Komolnagar",
          "Raipur",
          "Ramganj",
        ],
      },
      {
        name: "Feni",
        upazilas: [
          ,
          "Feni Sadar",
          "Daganbhuiyan",
          "Chhagalnaiya",
          "Porshuram",
          "Fulgazi",
          "Sonagazi",
        ],
      },
      {
        name: "Khagrachhari",
        upazilas: [
          "Khagrachhari Sadar",
          "Panchhari",
          "Dighinala",
          "Manikchhari",
          "Lakshmichhari",
          "Ramgarh",
          "Mahalchhari",
          "Matiranga",
        ],
      },
      {
        name: "Bandarban",
        upazilas: [
          "Bandarban Sadar",
          "Lama",
          "Thanchi",
          "Alikadam",
          "Ruma",
          "Naikhongchhari",
          "Rowangcchari",
        ],
      },
      {
        name: "Rangamati",
        upazilas: [
          "Rangamati Sadar",
          "Kaptai",
          "Kaukhali",
          "Nannerchar",
          "Bagaichhari",
          "Juraichhari",
          "Rajasthali",
          "Belaichhari",
          "Barkal",
          "Langadu",
        ],
      },
      {
        name: "Cox's Bazar",
        upazilas: [
          "Cox's Bazar Sadar",
          "Teknaf",
          "Chakaria",
          "Maheshkhali",
          "Pekua",
          "Kutubdia",
          "Ukhia",
          "Ramu",
        ],
      },
    ],
  },
  {
    name: "Sylhet",
    value: "Sy",
    districts: [
      {
        name: "Sylhet",
        upazilas: [
          "Sylhet Sadar",
          "Beanibazar",
          "Golapganj",
          "Companiganj",
          "Fenchuganj ",
          "Bishwanath",
          "Gowainghat",
          "Jaintiapur",
          "Kanaighat",
          "Balaganj",
          "South Shurma",
          "Zakiganj",
        ],
      },
      {
        name: "Sunamganj",
        upazilas: [
          "Sunamganj Sadar",
          "Sunamganj South",
          "Chhatak",
          "Jagannathpur",
          "Bishwamvarpur",
          "Tahirpur",
          "Derai",
          "Dharampasha",
          "Sulla",
          "Dowarabazar",
          "Jamalganj",
        ],
      },
      {
        name: "Moulvibazar",
        upazilas: [
          "Moulvibazar Sadar",
          "SreeMangal",
          "Kulaura",
          "Kamalganj",
          "Juri",
          "Barlekha",
          "Rajnagar",
        ],
      },
      {
        name: "Habiganj",
        upazilas: [
          "Habiganj Sadar",
          "Lakhai",
          "Madhabpur",
          "Nabiganj",
          "Chunarughat",
          "Baniachang",
          "Bahubal ",
          "Ajmiriganj",
        ],
      },
    ],
  },
];
